#!/usr/bin/env bash

PREFERENCES_KITTY=$PREFERENCES_DIR/kitty
PREFERENCES_KITTY_FONTS=$PREFERENCES_KITTY/fonts

PREFERENCES_KITTY_LOCAL=$HOME/.config/kitty

PREFERENCES_WORKSPACE_KITTY="$(workspace kitty)"

