#!/usr/bin/env python3
"""Compile canonical font settings into setTermFont() for Apple Terminal.

Output file: .workspace/term/font/apple_terminal.sh
"""

import json
import os
from pathlib import Path
import sys

# Ensure .workspace/share/python is in sys.path for direct script execution
_pref_ws = Path(
    os.environ.get(
        "PREFERENCES_WORKSPACE",
        Path(__file__).resolve().parents[2] / ".workspace",
    )
)
_ws_python = _pref_ws / "share" / "python"
if str(_ws_python) not in sys.path:
    sys.path.insert(0, str(_ws_python))

from util.path import (  # pylint: disable=wrong-import-position
    preferences_get_dir,
    preferences_get_workspace_dir,
)


def get_paths():
    """Get source themes directory and target output file path."""
    themes_dir = preferences_get_dir() / "term" / "theme"
    output_file = (
        preferences_get_workspace_dir("term") / "font" / "apple_terminal.sh"
    )
    return themes_dir, output_file


def compile_apple_terminal():
    """Compile Apple Terminal font definitions from theme JSON files."""
    themes_dir, output_file = get_paths()

    if not themes_dir.exists():
        print(f"Error: Directory not found: {themes_dir}", file=sys.stderr)
        sys.exit(1)

    json_files = sorted(themes_dir.glob("*.json"))
    if not json_files:
        print(f"Warning: No themes found in {themes_dir}", file=sys.stderr)
        return

    output_file.parent.mkdir(parents=True, exist_ok=True)

    cases = []
    default_font = "Monaco"
    default_size = "20"

    for json_file in json_files:
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            raw_name = data.get("name", json_file.stem)
            font_data = data.get("font", {})
            font_name = font_data.get("family", default_font)
            raw_size = font_data.get("size", default_size)
            font_size = str(int(float(raw_size)))

            if raw_name == "default":
                default_font = font_name
                default_size = font_size
            else:
                cases.append(
                    f"        '{raw_name}')\n"
                    f"            font='{font_name}'\n"
                    f"            size='{font_size}'\n"
                    f"            ;;"
                )
        except (json.JSONDecodeError, OSError) as e:
            print(f"Error processing {json_file}: {e}", file=sys.stderr)

    cases_block = "\n".join(cases)

    script_content = f"""#!/usr/bin/env bash
# Auto-generated by term/compile/compile_apple_terminal.py - Do not edit manually

function setTermFont {{
    local name=$1
    local font=''
    local size=''

    case $name in
{cases_block}
        *)
            font='{default_font}'
            size='{default_size}'
            ;;
    esac

    osascript -e "tell application \\"Terminal\\" to set the font name of window 1 to \\"$font\\"" 2>/dev/null || true
    osascript -e "tell application \\"Terminal\\" to set the font size of window 1 to $size" 2>/dev/null || true
}}
"""

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(script_content)

    print(f"✓ Compiled Apple Terminal fonts to {output_file}")


if __name__ == "__main__":
    compile_apple_terminal()
