#!/usr/bin/env python3
"""Compile canonical JSON themes into AOT ANSI OSC escape sequences.

Output file: .workspace/term/theme/compiled_osc.sh
"""

import json
import os
from pathlib import Path
import sys

# Ensure .workspace/share/python is in sys.path for direct script execution
_pref_ws = Path(
    os.environ.get(
        "PREFERENCES_WORKSPACE",
        Path(__file__).resolve().parents[2] / ".workspace",
    )
)
_ws_python = _pref_ws / "share" / "python"
if str(_ws_python) not in sys.path:
    sys.path.insert(0, str(_ws_python))

from util.path import (  # pylint: disable=wrong-import-position
    preferences_get_dir,
    preferences_get_workspace_dir,
)


def get_paths():
    """Get source themes directory and target output file path."""
    themes_dir = preferences_get_dir() / "term" / "theme"
    output_osc_file = (
        preferences_get_workspace_dir("term") / "theme" / "compiled_osc.sh"
    )
    return themes_dir, output_osc_file


def format_osc_sequence(theme_data: dict) -> str:
    """Build chained ANSI OSC escape sequence string for a theme."""
    parts = []
    color_data = theme_data.get("color", theme_data)

    # Foreground (OSC 10)
    if "foreground" in color_data:
        val = color_data["foreground"]
        parts.append(f"\\033]10;{val}\\007")

    # Background (OSC 11)
    if "background" in color_data:
        val = color_data["background"]
        parts.append(f"\\033]11;{val}\\007")

    # Cursor (OSC 12)
    if "cursor" in color_data:
        val = color_data["cursor"]
        parts.append(f"\\033]12;{val}\\007")

    # Selection Background & Foreground (OSC 17 & 19)
    if "selection_background" in color_data:
        val = color_data["selection_background"]
        parts.append(f"\\033]17;{val}\\007")
    if "selection_foreground" in color_data:
        val = color_data["selection_foreground"]
        parts.append(f"\\033]19;{val}\\007")

    # 16 ANSI Palette Colors (OSC 4;0..15)
    ansi_parts = []
    for i in range(16):
        key = f"color{i}"
        if key in color_data:
            val = color_data[key]
            ansi_parts.append(f"{i};{val}")

    if ansi_parts:
        joined = ";".join(ansi_parts)
        parts.append(f"\\033]4;{joined}\\007")

    return "".join(parts)


def compile_themes():
    """Compile all theme JSON files into shell export definitions."""
    themes_dir, output_osc_file = get_paths()

    if not themes_dir.exists():
        print(f"Error: Directory not found: {themes_dir}", file=sys.stderr)
        sys.exit(1)

    json_files = sorted(themes_dir.glob("*.json"))
    if not json_files:
        print(f"Warning: No themes found in {themes_dir}", file=sys.stderr)
        return

    output_osc_file.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by term/bin/compile_themes.py - Do not edit manually",
        "",
    ]

    count = 0
    for json_file in json_files:
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            raw_name = data.get("name", json_file.stem)
            theme_name = raw_name.upper()
            var_name = f"_PREFERENCES_TERM_{theme_name}"
            osc_seq = format_osc_sequence(data)

            lines.append(f"export {var_name}=$'{osc_seq}'")
            count += 1
        except (json.JSONDecodeError, OSError) as e:
            print(f"Error processing {json_file}: {e}", file=sys.stderr)

    lines.append("")

    with open(output_osc_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"✓ Compiled {count} themes to {output_osc_file}")


if __name__ == "__main__":
    compile_themes()
