#!/usr/bin/env python3
"""Compile canonical font settings into setTermFont() for GNOME Terminal.

Output file: .workspace/term/font/gnome_terminal.sh
"""

import json
import os
from pathlib import Path
import sys

# Ensure .workspace/share/python is in sys.path for direct script execution
_pref_ws = Path(
    os.environ.get(
        "PREFERENCES_WORKSPACE",
        Path(__file__).resolve().parents[2] / ".workspace",
    )
)
_ws_python = _pref_ws / "share" / "python"
if str(_ws_python) not in sys.path:
    sys.path.insert(0, str(_ws_python))

from util.path import (  # pylint: disable=wrong-import-position
    preferences_get_dir,
    preferences_get_workspace_dir,
)


def get_paths():
    """Get source themes directory and target output file path."""
    themes_dir = preferences_get_dir() / "term" / "theme"
    output_file = (
        preferences_get_workspace_dir("term") / "font" / "gnome_terminal.sh"
    )
    return themes_dir, output_file


def compile_gnome_terminal():
    """Compile GNOME Terminal font definitions from theme JSON files."""
    themes_dir, output_file = get_paths()

    if not themes_dir.exists():
        print(f"Error: Directory not found: {themes_dir}", file=sys.stderr)
        sys.exit(1)

    json_files = sorted(themes_dir.glob("*.json"))
    if not json_files:
        print(f"Warning: No themes found in {themes_dir}", file=sys.stderr)
        return

    output_file.parent.mkdir(parents=True, exist_ok=True)

    cases = []
    default_font_desc = "Ubuntu Mono 20"

    for json_file in json_files:
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            raw_name = data.get("name", json_file.stem)
            font_data = data.get("font", {})
            font_name = font_data.get("family", "Ubuntu Mono")
            raw_size = font_data.get("size", "20")
            font_size = str(int(float(raw_size)))
            font_desc = f"{font_name} {font_size}"

            if raw_name == "default":
                default_font_desc = font_desc
            else:
                cases.append(
                    f"        '{raw_name}')\n"
                    f"            fontDesc='{font_desc}'\n"
                    f"            ;;"
                )
        except (json.JSONDecodeError, OSError) as e:
            print(f"Error processing {json_file}: {e}", file=sys.stderr)

    cases_block = "\n".join(cases)

    script_content = f"""#!/usr/bin/env bash
# Auto-generated by term/compile/compile_gnome_terminal.py - Do not edit manually

function setTermFont {{
    local name=$1
    local fontDesc=''

    case $name in
{cases_block}
        *)
            fontDesc='{default_font_desc}'
            ;;
    esac

    local profile
    profile=$(gsettings get org.gnome.Terminal.ProfilesList default 2>/dev/null | tr -d "\\'")
    local schema="org.gnome.Terminal.Legacy.Profile"
    local path="/org/gnome/terminal/legacy/profiles:/:${{profile}}/"
    if [ -n "$profile" ]; then
        gsettings set "${{schema}}:${{path}}" \\
            font "$fontDesc" 2>/dev/null || true
    fi
}}
"""

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(script_content)

    print(f"✓ Compiled GNOME Terminal fonts to {output_file}")


if __name__ == "__main__":
    compile_gnome_terminal()
