#!/usr/bin/env python3
"""
Compile canonical font settings in term/theme/*.json into
an Ahead-Of-Time (AOT) setTermFont() function for Apple Terminal
in .workspace/term/font/apple_terminal.sh.
"""

import json
import os
import sys
from pathlib import Path


def get_paths():
    script_dir = Path(__file__).resolve().parent
    term_dir = script_dir.parent
    preferences_dir = term_dir.parent

    env_pref_dir = os.environ.get("PREFERENCES_DIR")
    if env_pref_dir:
        preferences_dir = Path(env_pref_dir)
        term_dir = preferences_dir / "term"

    themes_dir = term_dir / "theme"
    ws_env = os.environ.get(
        "PREFERENCES_WORKSPACE", str(preferences_dir / ".workspace")
    )
    workspace_dir = Path(ws_env)
    output_file = workspace_dir / "term" / "font" / "apple_terminal.sh"

    return themes_dir, output_file


def compile_apple_terminal():
    themes_dir, output_file = get_paths()

    if not themes_dir.exists():
        print(f"Error: Directory not found: {themes_dir}", file=sys.stderr)
        sys.exit(1)

    json_files = sorted(themes_dir.glob("*.json"))
    if not json_files:
        print(f"Warning: No themes found in {themes_dir}", file=sys.stderr)
        return

    output_file.parent.mkdir(parents=True, exist_ok=True)

    cases = []
    default_font = "Monaco"
    default_size = "20"

    for json_file in json_files:
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            raw_name = data.get("name", json_file.stem)
            font_data = data.get("font", {})
            font_name = font_data.get("family", default_font)
            raw_size = font_data.get("size", default_size)
            font_size = str(int(float(raw_size)))

            if raw_name == "default":
                default_font = font_name
                default_size = font_size
            else:
                cases.append(
                    f"        '{raw_name}')\n"
                    f"            font='{font_name}'\n"
                    f"            size='{font_size}'\n"
                    f"            ;;"
                )
        except (json.JSONDecodeError, OSError) as e:
            print(f"Error processing {json_file}: {e}", file=sys.stderr)

    cases_block = "\n".join(cases)

    script_content = f"""#!/usr/bin/env bash
# Auto-generated by term/compile/compile_apple_terminal.py - Do not edit manually

function setTermFont {{
    local name=$1
    local font=''
    local size=''

    case $name in
{cases_block}
        *)
            font='{default_font}'
            size='{default_size}'
            ;;
    esac

    osascript -e "tell application \\"Terminal\\" to set the font name of window 1 to \\"$font\\"" 2>/dev/null || true
    osascript -e "tell application \\"Terminal\\" to set the font size of window 1 to $size" 2>/dev/null || true
}}
"""

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(script_content)

    print(f"✓ Compiled Apple Terminal fonts to {output_file}")


if __name__ == "__main__":
    compile_apple_terminal()
