#!/usr/bin/env bash

source $PREFERENCES_DIR/util/override.sh

PREFERENCES_GIT=$PREFERENCES_DIR/git

if type -t __git_ps1 | grep -q '^function$' 2>/dev/null; then
    GIT_PS1_SHOWDIRTYSTATE=true
    GIT_PS1_SHOWSTASHSTATE=true
    GIT_PS1_SHOWUNTRACKEDFILES=true
    GIT_PS1_SHOWUPSTREAM="auto"
    GIT_PS1_SHOWCOLORHINTS=true

    PS1='\[\033[0;32m\]\u\[\e[0m\]:\w\[\033[0;33m\]$(__git_ps1)\[\e[0m\]# '
fi

export GIT_EDITOR=vim

wrapParameterBind git "-c include.path=$PREFERENCES_GIT/config -c core.excludesfile=$PREFERENCES_GIT/ignore"

