#!/usr/bin/env bash

source $PREFERENCES_DIR/util/override.sh
source $PREFERENCES_DIR/util/utils.sh
source $PREFERENCES_DIR/git/common.sh

if ! complete -p git &> /dev/null; then
    source $PREFERENCES_WORKSPACE_GIT_COMPLETION
fi

if ! type -t __git_ps1 | grep -q '^function$' 2>/dev/null; then
    source $PREFERENCES_WORKSPACE_GIT_PROMPT
fi

GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="auto"

function PREFERENCES_GIT_PS1 {
    __git_ps1
}

export GIT_EDITOR=vim

wrap '
    local config=$(findNearestParent $PWD ".gitconfig")
    if [ -z "$config" ]; then
        config=$PREFERENCES_WORKSPACE_GIT/config
    fi
' '' git '-c include.path=$config -c include.path=$PREFERENCES_WORKSPACE_GIT/config'
