#!/usr/bin/env bash

PREFERENCES_WORKSPACE_GIT="$(workspace git)"
PREFERENCES_WORKSPACE_GIT_COMPLETION="$PREFERENCES_WORKSPACE_GIT/git-completion.bash"
PREFERENCES_WORKSPACE_GIT_PROMPT="$PREFERENCES_WORKSPACE_GIT/git-prompt.sh"

