" Detect OS - Linux | Windows | Darwin
if !exists('g:os')
    if has('win64') || has('win32') || has('win16')
        let g:os = 'Windows'
    else
        let g:os = substitute(system('uname'), '\n', '', '')
    endif
endif

" vimrc dir
let g:vimrcDir = fnamemodify(resolve(expand('<sfile>:p')), ':h')

function s:getConfigPath(configPath) abort
    return g:vimrcDir . '/' . a:configPath
endfunction

function LoadConfig(configPath) abort
    let file = s:getConfigPath(a:configPath)
    if filereadable(file)
        exec 'source' file
    endif
endfunction


call LoadConfig('config/utils.vim')
call LoadConfig('config/plugins.vim')
call LoadConfig('config/setting.vim')
call LoadConfig('config/autocmd.vim')
call LoadConfig('config/keymap.vim')

