set nocompatible

" Detect OS - Linux | Windows | Darwin
if !exists('g:os')
    if has('win64') || has('win32') || has('win16')
        let g:os = 'Windows'
    else
        let g:os = substitute(system('uname'), '\n', '', '')
    endif
endif

" vimrc dir
let g:vimrcDir = fnamemodify(resolve(expand('<sfile>:p')), ':h')

function! g:LoadConfig(configPath) abort
    let file = g:vimrcDir . '/' . a:configPath
    if filereadable(file)
        execute 'source' file
    endif
endfunction

call g:LoadConfig('config/utils.vim')
call g:LoadConfig('config/plugins.vim')
call g:LoadConfig('config/setting.vim')
call g:LoadConfig('config/autocmd.vim')
call g:LoadConfig('config/lists.vim')
call g:LoadConfig('config/keymap.vim')
