#!/usr/bin/env bash

PREFERENCES_TERM=$PREFERENCES_DIR/term

source $PREFERENCES_TERM/util.sh

loadTerms

function vimTerm {
    trap defaultTerm RETURN
    setTerm vim
}
wrapPreHook vimTerm vim
wrapPreHook vimTerm vimdiff

function sshTerm {
    trap defaultTerm RETURN
    local confirmed=false
    function setTermAndBreak {
        setTerm $1 $2
        confirmed=true
    }

    for argu in $@
    do
        # For the usage xxx@bind_addr
        arguhost=${argu#*@}

        case $arguhost in
            -*) ;;
            prod.*) setTermAndBreak prod $argu ;;
            uat.*) setTermAndBreak uat $argu ;;
            docker.* | container.*) setTermAndBreak container $argu ;;
            *) setTermAndBreak remote $argu ;;
        esac

        [ $confirmed = true ] && break;
    done
}
wrapPreHook sshTerm ssh

defaultTerm

