# Pinkie Color Theme (Dark Pink / Hybrid)
background #682547
foreground #e8e6e8

# Cursor
cursor #f2e8ec
cursor_text_color #682547

# Selection
selection_background #8a345e
selection_foreground #ffffff

# Normal colors
color0 #231821
color1 #e05a6f
color2 #72c082
color3 #eec95e
color4 #6ca7d6
color5 #d18ecb
color6 #62c6b8
color7 #d8dade

# Bright colors
color8 #523e4d
color9 #ff758c
color10 #8eed97
color11 #ffec78
color12 #93c5f5
color13 #e8a8e3
color14 #8ae4d5
color15 #ffffff
