#!/usr/bin/env bash
# File: network/common.sh

PREFERENCES_NETWORK="$PREFERENCES_DIR/network"
PREFERENCES_NETWORK_BIN="$PREFERENCES_NETWORK/bin"
PREFERENCES_NETWORK_RUNNER="$PREFERENCES_NETWORK_BIN/preferences-network-runner.py"
PREFERENCES_WORKSPACE_NETWORK="$(workspace network)"
PREFERENCES_NETWORK_LOG="$PREFERENCES_WORKSPACE_NETWORK/network.log"
