#!/usr/bin/env bash

PREFERENCES_WORKSPACE_DOCKER="$(workspace docker)"
PREFERENCES_WORKSPACE_DOCKER_COMPLETION="$PREFERENCES_WORKSPACE_DOCKER/docker_completion.bash"
PREFERENCES_WORKSPACE_DOCKER_KUBECTL_COMPLETION="$PREFERENCES_WORKSPACE_DOCKER/kubectl_completion.bash"
