#!/usr/bin/env bash
# File: cron/common.sh

PREFERENCES_CRON="$PREFERENCES_DIR/cron"
PREFERENCES_CRON_BIN="$PREFERENCES_CRON/bin"
PREFERENCES_CRON_RUNNER="$PREFERENCES_CRON_BIN/preferences-cron-runner"
PREFERENCES_WORKSPACE_CRON="$(workspace cron)"
PREFERENCES_CRON_LOG="$PREFERENCES_WORKSPACE_CRON/cron.log"
