#!/usr/bin/env python3
"""
Compile canonical JSON themes from term/theme/*.json
into combined Kitty configuration format (.workspace/kitty/theme/*.conf)
containing font and color definitions (excluding font_size to prevent collisions),
and compute canonical relative font offsets in .workspace/kitty/font_offsets.json.
"""

import json
from pathlib import Path

from util.path import preferences_get_dir, preferences_get_workspace_dir


def format_kitty_font(font_data: dict) -> list[str]:
    """Format font directives for kitty configuration (omits font_size to prevent config collisions)."""
    if not font_data:
        return []

    lines = [
        "#: Fonts",
    ]
    if "family" in font_data:
        lines.append(f'font_family      {font_data["family"]}')
    if "bold" in font_data:
        lines.append(f'bold_font        {font_data["bold"]}')
    if "italic" in font_data:
        lines.append(f'italic_font      {font_data["italic"]}')
    if "bold_italic" in font_data:
        lines.append(f'bold_italic_font {font_data["bold_italic"]}')

    lines.append("")
    return lines


def format_kitty_color(color_data: dict) -> list[str]:
    """Format color directives for kitty configuration."""
    if not color_data:
        return []

    lines = [
        "#: Colors",
    ]
    for key in [
        "background",
        "foreground",
        "cursor",
        "cursor_text_color",
        "selection_background",
        "selection_foreground",
    ]:
        if key in color_data:
            lines.append(f"{key} {color_data[key]}")

    for i in range(16):
        key = f"color{i}"
        if key in color_data:
            lines.append(f"{key} {color_data[key]}")

    lines.append("")
    return lines


def format_kitty_conf(theme_data: dict) -> str:
    """Build unified kitty .conf profile content (font + color)."""
    lines = [
        "# Auto-generated by kitty/bin/compile_themes.py - Do not edit",
        "",
    ]

    font_data = theme_data.get("font", {})
    lines.extend(format_kitty_font(font_data))

    color_data = theme_data.get("color", theme_data)
    lines.extend(format_kitty_color(color_data))

    return "\n".join(lines) + "\n"


def generate_font_offsets_and_init_device_conf(themes_json_dir: Path, workspace_kitty_dir: Path) -> dict:
    """Extract relative font size offsets and initialize device_font.conf with default_size."""
    default_json = themes_json_dir / "default.json"
    default_size = 20.0
    if default_json.exists():
        try:
            with open(default_json, "r", encoding="utf-8") as f:
                default_data = json.load(f)
                default_size = float(
                    default_data.get("font", {}).get("size", default_size)
                )
        except Exception:
            pass

    # 1. Initialize device_font.conf if missing
    device_font_conf = workspace_kitty_dir / "device_font.conf"
    if not device_font_conf.exists():
        workspace_kitty_dir.mkdir(parents=True, exist_ok=True)
        with open(device_font_conf, "w", encoding="utf-8") as f:
            f.write(f"font_size {default_size:.1f}\n")

    # 2. Extract canonical relative offsets map
    offsets = {}
    for json_file in sorted(themes_json_dir.glob("*.json")):
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            name = data.get("name", json_file.stem)
            font_size = float(data.get("font", {}).get("size", default_size))
            offsets[name] = round(font_size - default_size, 1)
        except Exception:
            pass

    offsets_file = workspace_kitty_dir / "font_offsets.json"
    offsets_file.parent.mkdir(parents=True, exist_ok=True)
    with open(offsets_file, "w", encoding="utf-8") as f:
        json.dump(offsets, f, indent=2)

    return offsets


def compile_themes():
    themes_json_dir = preferences_get_dir() / "term" / "theme"
    workspace_kitty_dir = preferences_get_workspace_dir("kitty")
    output_kitty_theme_dir = workspace_kitty_dir / "theme"

    if not themes_json_dir.exists():
        print(
            f"Warning: Theme directory not found: {themes_json_dir}",
            file=sys.stderr,
        )
        return

    json_files = sorted(themes_json_dir.glob("*.json"))
    if not json_files:
        print(
            f"Warning: No theme JSON files in {themes_json_dir}",
            file=sys.stderr,
        )
        return

    output_kitty_theme_dir.mkdir(parents=True, exist_ok=True)

    # Generate font offsets and initialize device_font.conf
    offsets = generate_font_offsets_and_init_device_conf(themes_json_dir, workspace_kitty_dir)

    count = 0
    for json_file in json_files:
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            raw_name = data.get("name", json_file.stem)
            kitty_conf_content = format_kitty_conf(data)
            output_file = output_kitty_theme_dir / f"{raw_name}.conf"

            with open(output_file, "w", encoding="utf-8") as out:
                out.write(kitty_conf_content)

            count += 1
        except (json.JSONDecodeError, OSError) as e:
            print(f"Error processing {json_file}: {e}", file=sys.stderr)

    print(
        f"✓ Compiled {count} unified Kitty profiles to {output_kitty_theme_dir}"
    )
    print(f"✓ Generated font offsets for {len(offsets)} profiles to {workspace_kitty_dir / 'font_offsets.json'}")


if __name__ == "__main__":
    compile_themes()
