#!/usr/bin/env python3
"""
Compile canonical JSON themes from term/theme/*.json
into combined Kitty configuration format (.workspace/kitty/theme/*.conf)
containing both font and color definitions.
"""

import json
import os
import sys
from pathlib import Path


def get_paths():
    script_dir = Path(__file__).resolve().parent
    kitty_dir = script_dir.parent
    preferences_dir = kitty_dir.parent

    env_pref_dir = os.environ.get("PREFERENCES_DIR")
    if env_pref_dir:
        preferences_dir = Path(env_pref_dir)

    themes_json_dir = preferences_dir / "term" / "theme"
    ws_env = os.environ.get(
        "PREFERENCES_WORKSPACE", str(preferences_dir / ".workspace")
    )
    workspace_dir = Path(ws_env)
    output_kitty_dir = workspace_dir / "kitty"
    output_kitty_theme_dir = output_kitty_dir / "theme"

    return themes_json_dir, output_kitty_theme_dir


def format_kitty_font(font_data: dict) -> list[str]:
    """Format font directives for kitty configuration."""
    if not font_data:
        return []

    lines = [
        "#: Fonts",
    ]
    if "family" in font_data:
        lines.append(f'font_family      {font_data["family"]}')
    if "bold" in font_data:
        lines.append(f'bold_font        {font_data["bold"]}')
    if "italic" in font_data:
        lines.append(f'italic_font      {font_data["italic"]}')
    if "bold_italic" in font_data:
        lines.append(f'bold_italic_font {font_data["bold_italic"]}')
    if "size" in font_data:
        lines.append(f'font_size        {font_data["size"]}')

    lines.append("")
    return lines


def format_kitty_color(color_data: dict) -> list[str]:
    """Format color directives for kitty configuration."""
    if not color_data:
        return []

    lines = [
        "#: Colors",
    ]
    for key in [
        "background",
        "foreground",
        "cursor",
        "cursor_text_color",
        "selection_background",
        "selection_foreground",
    ]:
        if key in color_data:
            lines.append(f"{key} {color_data[key]}")

    for i in range(16):
        key = f"color{i}"
        if key in color_data:
            lines.append(f"{key} {color_data[key]}")

    lines.append("")
    return lines


def format_kitty_conf(theme_data: dict) -> str:
    """Build unified kitty .conf profile content (font + color)."""
    lines = [
        "# Auto-generated by kitty/bin/compile_themes.py - Do not edit",
        "",
    ]

    font_data = theme_data.get("font", {})
    lines.extend(format_kitty_font(font_data))

    color_data = theme_data.get("color", theme_data)
    lines.extend(format_kitty_color(color_data))

    return "\n".join(lines) + "\n"


def compile_themes():
    themes_json_dir, output_kitty_theme_dir = get_paths()

    if not themes_json_dir.exists():
        print(
            f"Warning: Theme directory not found: {themes_json_dir}",
            file=sys.stderr,
        )
        return

    json_files = sorted(themes_json_dir.glob("*.json"))
    if not json_files:
        print(
            f"Warning: No theme JSON files in {themes_json_dir}",
            file=sys.stderr,
        )
        return

    output_kitty_theme_dir.mkdir(parents=True, exist_ok=True)

    count = 0
    for json_file in json_files:
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            raw_name = data.get("name", json_file.stem)
            kitty_conf_content = format_kitty_conf(data)
            output_file = output_kitty_theme_dir / f"{raw_name}.conf"

            with open(output_file, "w", encoding="utf-8") as out:
                out.write(kitty_conf_content)

            count += 1
        except (json.JSONDecodeError, OSError) as e:
            print(f"Error processing {json_file}: {e}", file=sys.stderr)

    print(
        f"✓ Compiled {count} unified Kitty profiles to {output_kitty_theme_dir}"
    )


if __name__ == "__main__":
    compile_themes()
