#!/usr/bin/env bash

source $PREFERENCES_DIR/util/override.sh

#localstack
wrap '' 'AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=${DEFAULT_REGION:-$AWS_DEFAULT_REGION} aws --endpoint-url=http://${LOCALSTACK_HOST:-localhost}:4566' awslocal

if ! command -v aws_completer &> /dev/null; then
    complete -C "$(which aws_completer)" aws
fi

