#!/usr/bin/env bash

source $PREFERENCES_DIR/util/override.sh

#localstack
wrap '' 'AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=${DEFAULT_REGION:-$AWS_DEFAULT_REGION} aws --endpoint-url=http://${LOCALSTACK_HOST:-localhost}:4566' awslocal

if ! command -v aws_completer &> /dev/null; then
    complete -C "$(which aws_completer)" aws
fi

function PREFERENCES_AWS_PS1 {
    local ret=""
    if [[ ! -z ${AWS_PROFILE:+x} ]]; then
        local second_to_expire=$(( ($(date -d $AWS_CREDENTIAL_EXPIRATION "+%s") - $(date "+%s")) ))
        if [[ second_to_expire -gt 0 ]]; then
            ret="{$AWS_PROFILE|$(date -u -d @${second_to_expire} +"%T")}"
        else
            export AWS_PROFILE=""
        fi
    fi

    echo $ret
}

function awsLogin {
    if [[ $# < 1 ]]; then
        echo "usage: ${FUNCNAME} [profile]"
        return
    fi

    local profile=$1
    aws sso login --profile $profile

    if [[ $? -eq 0 ]]; then
        export AWS_PROFILE=$profile
        eval $(aws configure export-credentials --profile $profile --format env)
    else
        echo "login $profile failed"
    fi
}

