#!/usr/bin/env bash

source $PREFERENCES_DIR/util/override.sh
source $PREFERENCES_DIR/util/utils.sh

source $PREFERENCES_DIR/python/common.sh
source $PREFERENCES_DIR/python/pvenv.sh

replace 'python' '' 'python3'

wrapParameterBind 'pylint' "--rcfile $PREFERENCES_WORKSPACE_PYTHON_PYLINTRC"

