#!/usr/bin/env bash

source $PREFERENCES_DIR/util/utils.sh
source $PREFERENCES_DIR/util/environment.sh

eachSubFile "$PREFERENCES_DIR" 'source' 'bashrc'

# Compose PS1 afterall
#PS1='\[\033[0;32m\]\u\[\e[0m\]:\w\[\033[0;33m\]$(PREFERENCES_GIT_PS1)\[\e[0m\]# $(PREFERENCES_AWS_PS1)'

PS1='\[\033[0;32m\]\u'
PS1+='\[\e[0m\]:\w'
PS1+='\[\033[0;33m\]$(PREFERENCES_GIT_PS1)'
PS1+='\[\033[1;36m\]$(PREFERENCES_AWS_PS1)'
PS1+='\[\e[0m\]# '

