sourceShare bash utils.sh 2>/dev/null || true
sourceShare bash override.sh 2>/dev/null || true

if [ ! -f "${PREFERENCES_WORKSPACE:-$PREFERENCES_DIR/.workspace}/bash/compiled_bashrc.sh" ]; then
    function addModuleBin {
        local modDir=$1
        if [ -d "$modDir/bin" ]; then
            export PATH="$modDir/bin:$PATH"
        fi
    }
    forEachModule addModuleBin
fi

export PATH=$HOME/bin:$HOME/.local/bin:$PREFERENCES_DIR/bin:$PATH

export EDITOR=vim
export VISUAL=vim

export LC_COLLATE=C
export LC_MESSAGES=C
export GTEST_COLOR=1

export LS_COLORS='no=00:fi=00:di=01;36:ln=02;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

wrapParameterBind 'ls' '--color=auto --time-style=long-iso'
wrapParameterBind 'grep' '--color=auto'

replace 'preferencesDir' '' 'cd "$PREFERENCES_DIR"'
replace 'preferencesWorkspace' '' 'cd "$(workspace)"'

[ -f "${PREFERENCES_WORKSPACE:-$PREFERENCES_DIR/.workspace}/bash/os.sh" ] && source "${PREFERENCES_WORKSPACE:-$PREFERENCES_DIR/.workspace}/bash/os.sh"

PS1='\[\033[0;32m\]\u'
PS1+='\[\e[0m\]:\w'
PS1+='\[\033[0;33m\]$(PREFERENCES_GIT_PS1)'
PS1+='\[\033[1;36m\]$(PREFERENCES_AWS_PS1)'
PS1+='\[\e[0m\]# '
