#!/usr/bin/env bash
# File: bash/common.sh

PREFERENCES_WORKSPACE_BASH="$(workspace bash)"
PREFERENCES_COMPILED_BASHRC="$PREFERENCES_WORKSPACE_BASH/compiled_bashrc.sh"

function compilePreferencesBashrc {
    local targetDir="$PREFERENCES_WORKSPACE_BASH"
    local targetFile="$PREFERENCES_COMPILED_BASHRC"

    mkdir -p "$targetDir"
    cat << 'EOF' > "$targetFile"
#!/usr/bin/env bash
# Auto-generated by preferences installer - Do not edit manually

export PREFERENCES_DIR="${PREFERENCES_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
source "$PREFERENCES_DIR/util/environment.sh" 2>/dev/null || true
source "$PREFERENCES_DIR/util/utils.sh" 2>/dev/null || true
source "$PREFERENCES_DIR/util/override.sh" 2>/dev/null || true
EOF

    _compileModuleEntry() {
        local modDir="${1%/}"
        local modName=$2

        if [ -d "$modDir/bin" ]; then
            echo "export PATH=\"$modDir/bin:\$PATH\"" >> "$targetFile"
        fi
        if [ -f "$modDir/bashrc" ]; then
            echo "[[ -f \"$modDir/bashrc\" ]] && source \"$modDir/bashrc\"" >> "$targetFile"
        fi
    }

    forEachModule _compileModuleEntry
    echo "✓ Compiled bashrc loader written to $targetFile"
}
