#!/usr/bin/env bash
# File: bash/common.sh

PREFERENCES_WORKSPACE_BASH="$(workspace bash)"
PREFERENCES_COMPILED_BASHRC="$PREFERENCES_WORKSPACE_BASH/compiled_bashrc.sh"

function aggregatePreferencesEnv {
    local rootDir="${1:-$PREFERENCES_DIR}"
    local wsDir="$(workspace '')"
    local pythonWsShare="$wsDir/share/python"

    mkdir -p "$pythonWsShare"

    local binPaths=()
    # Add root bin if it exists
    [ -d "$rootDir/bin" ] && binPaths+=("$rootDir/bin")

    _discoverModuleEnv() {
        local modDir="${1%/}"
        local modName=$2

        # 1. PATH: Check for module bin/
        if [ -d "$modDir/bin" ]; then
            binPaths+=("$modDir/bin")
        fi

        # 2. PYTHONPATH: Check for module share/python/
        if [ -d "$modDir/share/python" ]; then
            local aliasName="$modName"
            [ "$modName" == "python" ] && aliasName="util"
            installPreferencesSymlink "$modDir/share/python" "$pythonWsShare/$aliasName"
            # If python module, also create alias 'python' for direct import compatibility
            if [ "$modName" == "python" ]; then
                installPreferencesSymlink "$modDir/share/python" "$pythonWsShare/python"
            fi
        fi
    }

    forEachModule _discoverModuleEnv "$rootDir"

    # Build PREFERENCES_PATH
    local joinedPath=""
    for bp in "${binPaths[@]}"; do
        if [ -z "$joinedPath" ]; then
            joinedPath="$bp"
        else
            joinedPath="$joinedPath:$bp"
        fi
    done

    export PREFERENCES_PATH="$joinedPath"
    export PREFERENCES_PYTHONPATH="$pythonWsShare"
    export PATH="$PREFERENCES_PATH:$PATH"
    export PYTHONPATH="$PREFERENCES_PYTHONPATH${PYTHONPATH:+:$PYTHONPATH}"
}

function compilePreferencesBashrc {
    local targetDir="$PREFERENCES_WORKSPACE_BASH"
    local targetFile="$PREFERENCES_COMPILED_BASHRC"

    # Ensure environment is aggregated first
    aggregatePreferencesEnv

    mkdir -p "$targetDir"

    cat << 'HEADER' > "$targetFile"
#!/usr/bin/env bash
# Auto-generated by preferences installer - Do not edit manually

export PREFERENCES_DIR="${PREFERENCES_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
source "$PREFERENCES_DIR/bootstrap.sh" 2>/dev/null || true
HEADER

    echo "export PREFERENCES_PATH=\"$PREFERENCES_PATH\"" >> "$targetFile"
    echo "export PREFERENCES_PYTHONPATH=\"$PREFERENCES_PYTHONPATH\"" >> "$targetFile"
    echo "export PATH=\"\$PREFERENCES_PATH:\$PATH\"" >> "$targetFile"
    echo "export PYTHONPATH=\"\$PREFERENCES_PYTHONPATH\${PYTHONPATH:+:\$PYTHONPATH}\"" >> "$targetFile"

    _compileModuleEntry() {
        local modDir="${1%/}"
        local modName=$2

        if [ -f "$modDir/bashrc" ]; then
            echo "[[ -f \"$modDir/bashrc\" ]] && source \"$modDir/bashrc\"" >> "$targetFile"
        fi
    }

    forEachModule _compileModuleEntry
    echo "✓ Compiled bashrc loader written to $targetFile"
}
