#!/usr/bin/env bash

PREFERENCES_ANTIGRAVITY=$PREFERENCES_DIR/antigravity

PREFERENCES_ANTIGRAVITY_LOCAL=$HOME/.config/antigravity

PREFERENCES_ANTIGRAVITY_GLOBAL_SKILLS=$HOME/.gemini/antigravity-cli/skills

PREFERENCES_WORKSPACE_ANTIGRAVITY="$(workspace antigravity)"
