#!/usr/bin/env bash

PREFERENCES_ANTIGRAVITY=$PREFERENCES_DIR/antigravity

PREFERENCES_ANTIGRAVITY_LOCAL=$HOME/.config/antigravity

PREFERENCES_ANTIGRAVITY_GLOBAL_CONFIG=$HOME/.gemini/antigravity-cli

PREFERENCES_ANTIGRAVITY_GLOBAL_SKILLS=$PREFERENCES_ANTIGRAVITY_GLOBAL_CONFIG/skills

PREFERENCES_WORKSPACE_ANTIGRAVITY="$(workspace antigravity)"
